language: java
jdk:
- openjdk8

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "dry/target/dry.jar"
    - "wet/target/wet.jar"
  skip_cleanup: true
  on:
    tags: true

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
