language: java
jdk:
- openjdk8
notifications:
  webhooks:
  - https://skrdylsvea.execute-api.us-east-2.amazonaws.com/default/TravisCI-DIscordWebhook

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "YOUR GIT USER NAME"
  - git config --local user.email "YOUR GIT USER EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "dry/target/dry.jar"
    - "wet/target/wet.jar"
  skip_cleanup: true
  on:
    branch: deploy
