language: java
jdk:
- openjdk8

before_deploy:
  - export TRAVIS_TAG=$(git log --format=%h -1)
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "dry/target/dry.jar"
    - "wet/target/wet.jar"
  skip_cleanup: true
  on:
    branch: release

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
