language: java
jdk:
- openjdk8
notifications:
  webhooks:
  - https://skrdylsvea.execute-api.us-east-2.amazonaws.com/default/TravisCI-DIscordWebhook

before_deploy:
  - export TRAVIS_TAG=$(git log --format=%h -1)
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "dry/target/dry.jar"
    - "wet/target/wet.jar"
  skip_cleanup: true
  on:
    branch: master
