logging:
  level:
    Root: info
    me.jbuelow.rov: debug

vehicle:
  name: Nautilus
  motor-configuration:
  - name: "Bow Port Thruster"
    motorType: THRUSTER
    motorOrientation: MULTI_AXIS
    pwm-port: 0
    thrustFactors:
      SWAY: -0.707
      SURGE: 0.707
      YAW: 1.000
  - name: "Bow Starboard Thruster"
    motorType: THRUSTER
    motorOrientation: MULTI_AXIS
    pwm-port: 1
    thrustFactors:
      SWAY: 0.707
      SURGE: 0.707
      YAW: -1.000
  - name: "Stern Port Thruster"
    motorType: THRUSTER
    motorOrientation: MULTI_AXIS
    pwm-port: 2
    thrustFactors:
      SWAY: -0.707
      SURGE: -0.707
      YAW: -1.000
  - name: "Stern Starboard Thruster"
    motorType: THRUSTER
    motorOrientation: MULTI_AXIS
    pwm-port: 3
    thrustFactors:
      SWAY: 0.707
      SURGE: -0.707
      YAW: 1.000
  - name: "Mid Port Thruster"
    motorType: THRUSTER
    motorOrientation: Z_AXIS
    pwm-port: 4
    thrustFactors:
      HEAVE: 1.000
      ROLL: -1.000
  - name: "Mid Starboard Thruster"
    motorType: THRUSTER
    motorOrientation: Z_AXIS
    pwm-port: 5
    thrustFactors:
      HEAVE: 1.000
      ROLL: 1.000
  servo-configuration:
  - name: "Claw"
    pwm-port: 6
  - name: "Magnet"
    pwm-port: 7
  - name: "Cup"
    pwm-port: 8
  video-configuration:
  - name: "Front Camera"
    videoStreamAddress: "localhost:1234"
    
  
   