logging:
  file: ROV.log
  level:
    Root: info
    me.jbuelow.rov: trace

vehicle:
  name: Nautilus
  motor-configuration:
  - name: "Bow Port Thruster"
    motorType: THRUSTER
    motorOrientation: MULTI_AXIS
    pwm-port: 0
    thrustFactors:
      SWAY: 1.000
      SURGE: 1.000
      YAW: 0.707
  - name: "Bow Starboard Thruster"
    motorType: THRUSTER
    motorOrientation: MULTI_AXIS
    pwm-port: 1
    thrustFactors:
      SWAY: 1.000 #inverted
      SURGE: -1.000 #inverted
      YAW: 0.707 #inverted
  - name: "Stern Port Thruster"
    motorType: THRUSTER
    motorOrientation: MULTI_AXIS
    pwm-port: 2
    thrustFactors:
      SWAY: 1.000 #inverted
      SURGE: -1.000 #inverted
      YAW: -0.707 #inverted
  - name: "Stern Starboard Thruster"
    motorType: THRUSTER
    motorOrientation: MULTI_AXIS
    pwm-port: 3
    thrustFactors:
      SWAY: 1.000
      SURGE: 1.000
      YAW: -0.707
  - name: "Mid Port Thruster"
    motorType: THRUSTER
    motorOrientation: Z_AXIS
    pwm-port: 4
    thrustFactors:
      HEAVE: -1.000 #inverted
      ROLL: 1.000 #inverted
  - name: "Mid Starboard Thruster"
    motorType: THRUSTER
    motorOrientation: Z_AXIS
    pwm-port: 5
    thrustFactors:
      HEAVE: 1.000
      ROLL: 1.000
  servo-configuration:
  - name: "Claw"
    pwm-port: 6
    tool: GRIPPER
  - name: "Magnet"
    pwm-port: 7
    tool: MAGNET
  - name: "Cup"
    pwm-port: 8
    tool: CUP
  - name: "Camera X"
    pwm-port: 9
    tool: CAMERA_X
  video-configuration:
  - name: "USB Camera"
    priority: true
    port: null
    fps: 30
    bitrate: 12000000

    
  
   